// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RFI.API.Data;

#nullable disable

namespace RFI.API.Migrations
{
    [DbContext(typeof(EventsDbContext))]
    [Migration("20260120124946_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("RFI.API.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailedContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 20, 12, 49, 44, 396, DateTimeKind.Utc).AddTicks(5896),
                            Description = "Justice for 30,000 Iranians - Crimes against humanity must be stopped.",
                            DetailedContent = "Iranians in Melbourne are gathering in front of Parliament House today from 4:00 pm to 6:00 pm to support King Reza Pahlavi and stand shoulder to shoulder with people inside Iran. Protesters are amplifying the voices of families demanding justice for more than 30,000 people killed by the regime and are calling for urgent international action to hold Tehran accountable for its crimes.",
                            EventDate = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrls = "[\"https://www.riseforiran.org/images/highlights/18Jan.png\"]",
                            IsActive = true,
                            Location = "Parliament House, Melbourne",
                            Title = "Parliament Steps Vigil Australia - Melbourne"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 20, 12, 49, 44, 396, DateTimeKind.Utc).AddTicks(5899),
                            Description = "Stand with Iran",
                            DetailedContent = "Details coming soon.",
                            EventDate = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrls = "[]",
                            IsActive = true,
                            Location = "TBD",
                            Title = "The Last Fight"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
