START TRANSACTION;

CREATE TABLE "Users" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "Username" TEXT NOT NULL,
    "PasswordHash" TEXT NOT NULL,
    "Role" TEXT NOT NULL,
    "CreatedAt" TEXT NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_Users_Username" ON "Users" ("Username");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260207073934_AddAuthenticationUsers', '8.0.11');

COMMIT;

